# Generated by Django 3.1.2 on 2021-05-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0002_auto_20210511_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docfile',
            new_name='subida',
        ),
    ]
